name: ci_pipeline_storage

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run npm build
        run: npm install && npm run build

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            KEY=$(az storage account keys list --resource-group "geekday-event-rg" --account-name "geekdayeventstorage" --query "[0].value" --output tsv)
            az storage blob upload-batch --account-name "geekdayeventstorage" --account-key="${KEY}" --destination "$web" --source "build"
