on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Create Debian package
        run: |
          VERSION=$(jq -r '.version' ./package.json)

          mkdir -p "prague-${VERSION}/DEBIAN"

          echo "Source: prague" >> "prague-${VERSION}/DEBIAN/control"
          echo "Section: utils" >> "prague-${VERSION}/DEBIAN/control"
          echo "Priority: optional" >> "prague-${VERSION}/DEBIAN/control"
          echo "Maintainer: Engin Polat <polatengin@hotmail.com>" >> "prague-${VERSION}/DEBIAN/control"
          echo "Build-Depends: debhelper-compat (= 13)" >> "prague-${VERSION}/DEBIAN/control"
          echo "Package: prague" >> "prague-${VERSION}/DEBIAN/control"
          echo "Version: ${VERSION}" >> "prague-${VERSION}/DEBIAN/control"
          echo "Architecture: all" >> "prague-${VERSION}/DEBIAN/control"
          echo "Depends: nodejs (>= 20.0.0), npm" >> "prague-${VERSION}/DEBIAN/control"
          echo "Description: Estimates the valuf of a given GitHub Account" >> "prague-${VERSION}/DEBIAN/control"

          echo "#!/bin/bash" >> "prague-${VERSION}/DEBIAN/postinst"
          echo "ln -s /usr/local/src/prague/index.js /usr/local/bin/prague" >> "prague-${VERSION}/DEBIAN/postinst"
          echo "exit 0" >> "prague-${VERSION}/DEBIAN/postinst"
          chmod +x "prague-${VERSION}/DEBIAN/postinst"

          echo "#!/usr/bin/make -f" >> "prague-${VERSION}/DEBIAN/rules"
          echo "" >> "prague-${VERSION}/DEBIAN/rules"
          echo "%:" >> "prague-${VERSION}/DEBIAN/rules"
          echo "	dh \$@" >> "prague-${VERSION}/DEBIAN/rules"

          echo "prague (${VERSION}) unstable; urgency=low" >> "prague-${VERSION}/DEBIAN/changelog"
          echo "" >> "prague-${VERSION}/DEBIAN/changelog"
          echo "  * Initial release of Prague." >> "prague-${VERSION}/DEBIAN/changelog"
          echo "" >> "prague-${VERSION}/DEBIAN/changelog"
          echo " -- Engin Polat <polatengin@hotmail.com>  Sun, 30 Sep 2024 00:00:00 +0000" >> "prague-${VERSION}/DEBIAN/changelog"

          mkdir -p "prague-${VERSION}/usr/local/src/prague"
          cp ./_dist/* "prague-${VERSION}/usr/local/src/prague"
          cp ./package.json "prague-${VERSION}/usr/local/src/prague"

          chmod +x "prague-${VERSION}/usr/local/src/prague/index.js"

          dpkg-deb --build "prague-${VERSION}"

      - name: "Create release"
        uses: "actions/github-script@v7"
        with:
          script: |
            const fs = require('fs');
            const path = './package.json';

            const version = JSON.parse(fs.readFileSync(path, 'utf8')).version;

            const tagResponse = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: version,
              message: `v${version}`,
              object: context.sha,
              type: 'commit'
            });
            const releaseResponse = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: false,
              name: version,
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              tag_name: version
            });
            const fileName = `prague-${version}.deb`;
            const debFileContent = fs.readFileSync(fileName);
            await github.rest.repos.uploadReleaseAsset({
              url: releaseResponse.data.upload_url,
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': debFileContent.length,
              },
              name: fileName,
              data: debFileContent,
            });
